In [1]:
import numpy as np

# Task 1 — Generate and Inspect Data
np.random.seed(42)

# generate 5x4 array with values between 50 and 100
scores = np.random.randint(50, 101, size=(5,4))

print("Scores Matrix:")
print(scores)

# score of 3rd student in 2nd subject
print("\nScore of 3rd student in 2nd subject:")
print(scores[2,1])

# scores of last 2 students
print("\nScores of last 2 students:")
print(scores[-2:])

# first 3 students, subjects 2 and 3
print("\nScores of first 3 students in subjects 2 and 3:")
print(scores[:3,1:3])


# Task 2 — Broadcasting Operations

# column-wise mean
column_mean = np.round(scores.mean(axis=0),2)
print("\nColumn-wise mean:")
print(column_mean)

# add curve using broadcasting
curve = np.array([5,3,7,2])
curved_scores = scores + curve

# ensure max score = 100
curved_scores = np.clip(curved_scores, None, 100)

print("\nCurved Scores:")
print(curved_scores)

# row-wise max
row_max = curved_scores.max(axis=1)
print("\nRow-wise max:")
print(row_max)


# Task 3 — Normalize and Identify

# row-wise min and max
row_min = curved_scores.min(axis=1, keepdims=True)
row_max = curved_scores.max(axis=1, keepdims=True)

# min-max normalization
normalized = (curved_scores - row_min) / (row_max - row_min)

print("\nNormalized scores:")
print(normalized)

# index of highest value in normalized array
max_index = np.unravel_index(np.argmax(normalized), normalized.shape)

print("\nIndex of highest normalized value (student,row , subject,column):")
print(max_index)

# scores strictly above 90
above_90 = curved_scores[curved_scores > 90]

print("\nScores above 90:")
print(above_90)

Scores Matrix:
[[88 78 64 92]
 [57 70 88 68]
 [72 60 60 73]
 [85 89 73 52]
 [71 51 73 93]]

Score of 3rd student in 2nd subject:
60

Scores of last 2 students:
[[85 89 73 52]
 [71 51 73 93]]

Scores of first 3 students in subjects 2 and 3:
[[78 64]
 [70 88]
 [60 60]]

Column-wise mean:
[74.6 69.6 71.6 75.6]

Curved Scores:
[[93 81 71 94]
 [62 73 95 70]
 [77 63 67 75]
 [90 92 80 54]
 [76 54 80 95]]

Row-wise max:
[94 95 77 92 95]

Normalized scores:
[[0.95652174 0.43478261 0.         1.        ]
 [0.         0.33333333 1.         0.24242424]
 [1.         0.         0.28571429 0.85714286]
 [0.94736842 1.         0.68421053 0.        ]
 [0.53658537 0.         0.63414634 1.        ]]

Index of highest normalized value (student,row , subject,column):
(np.int64(0), np.int64(3))

Scores above 90:
[93 94 95 92 95]
